public boolean isCodeDisabled() {
    if (isCodeAutogenerated()) {
        return true;
    }
    org.libreplan.business.orders.entities.OrderElement orderElement = orderElementModel.getOrderElement();
    if (orderElement == null) {
        return false;
    }
    return orderElement.isJiraIssue();
}