public static java.sql.PreparedStatement create(java.sql.Connection connection, java.lang.String sql, int autoGeneratedKeys) throws java.sql.SQLException {
    java.sql.PreparedStatement preparedStatement = connection.prepareStatement(sql, autoGeneratedKeys);
    return jodd.db.debug.LoggablePreparedStatementFactory.wrap(preparedStatement, sql);
}