public boolean isCodeDisabled() {
    if (isCodeAutogenerated()) {
        return true;
    }
    org.libreplan.business.orders.entities.OrderElement orderElement = orderElementModel.getOrderElement();
    return (orderElement != null) && (orderElement.isJiraIssue());
}