public java.sql.PreparedStatement create(java.sql.Connection connection, java.lang.String sql, int autoGeneratedKeys) throws java.sql.SQLException {
    java.sql.PreparedStatement preparedStatement = connection.prepareStatement(sql, autoGeneratedKeys);
    return wrap(preparedStatement, sql);
}