public static java.lang.String AutoGeneratedInformationTextHTML() {
    java.lang.String outTextResult = "";
    if ((tel_ran.tests.controller.Maintenance.AutoGeneratedInformationTextHTML) != null) {
        outTextResult = tel_ran.tests.controller.Maintenance.AutoGeneratedInformationTextHTML.toString();
        tel_ran.tests.controller.Maintenance.AutoGeneratedInformationTextHTML.delete(0, tel_ran.tests.controller.Maintenance.AutoGeneratedInformationTextHTML.length());
    }
    return outTextResult;
}