private org.libreplan.business.workreports.entities.WorkReportLine createWorkReportLine(org.libreplan.business.orders.entities.OrderElement orderElement, org.joda.time.LocalDate date) {
    org.libreplan.business.workreports.entities.WorkReportLine workReportLine = org.libreplan.business.workreports.entities.WorkReportLine.create(workReport);
    workReportLine.setCodeAutogenerated(true);
    workReportLine.setOrderElement(orderElement);
    workReportLine.setDate(date.toDateTimeAtStartOfDay().toDate());
    workReportLine.bindTypeOfWorkHours();
    if ((workReportLine.getTypeOfWorkHours()) == null) {
        org.libreplan.web.users.dashboard.PersonalTimesheetModel.LOG.info("workReportLine.getTypeOfWorkHours() je null!");
    }
    workReportLine.setEffort(org.libreplan.business.workingday.EffortDuration.zero());
    return workReportLine;
}