public void onCheckGenerateCode(org.zkoss.zk.ui.event.Event e) {
    org.zkoss.zk.ui.event.CheckEvent ce = ((org.zkoss.zk.ui.event.CheckEvent) (e));
    if (ce.isChecked()) {
        try {
            workerModel.setCodeAutogenerated(ce.isChecked());
        } catch (java.util.ConcurrentModificationException err) {
            messages.showMessage(Level.ERROR, err.getMessage());
        }
    }
    org.libreplan.web.common.Util.reloadBindings(editWindow);
}