@retrofit2.http.FormUrlEncoded
@retrofit2.http.Headers(value = "X-API-KEY:80w0g4o84wsc4gsc804c08scs00w8co4wscg848c")
@retrofit2.http.POST(value = "main/add_order/format/json")
retrofit2.Call<app.nutrimeat.meat.org.nutrimeat.Checkout.AddOrderItemResponse> addOrder(@retrofit2.http.Field(value = "order_no")
java.lang.String orderNo, @retrofit2.http.Field(value = "email")
java.lang.String email, @retrofit2.http.Field(value = "order_total_no_discount")
int orderTotalDiscount, @retrofit2.http.Field(value = "discount_desc")
java.lang.String discountDesc, @retrofit2.http.Field(value = "discount_amount")
float discountAmount, @retrofit2.http.Field(value = "order_total")
double orderTotal, @retrofit2.http.Field(value = "items")
int items, @retrofit2.http.Field(value = "total_weight")
int totalWeight, @retrofit2.http.Field(value = "ord_status")
int orderStatus, @retrofit2.http.Field(value = "ord_date_time")
java.lang.String orderDateTime, @retrofit2.http.Field(value = "ord_name")
java.lang.String orderName, @retrofit2.http.Field(value = "ord_address")
java.lang.String orderAddress, @retrofit2.http.Field(value = "ord_city")
java.lang.String orderCity, @retrofit2.http.Field(value = "ord_state")
java.lang.String orderState, @retrofit2.http.Field(value = "ord_country")
java.lang.String orderCountry, @retrofit2.http.Field(value = "ord_postal")
java.lang.String postal, @retrofit2.http.Field(value = "ord_store")
java.lang.String orderStore, @retrofit2.http.Field(value = "ord_phone")
java.lang.String phone, @retrofit2.http.Field(value = "ord_payment_mode")
java.lang.String paymentMode, @retrofit2.http.Field(value = "ord_type")
java.lang.String orderType, @retrofit2.http.Field(value = "ord_pre_date")
java.lang.String orderPreDate, @retrofit2.http.Field(value = "ord_pre_time")
java.lang.String orderPreTime, @retrofit2.http.Field(value = "ord_online_transaction")
java.lang.String onlineTransaction);