protected java.sql.PreparedStatement createPreparedStatement(java.sql.Connection connection, java.lang.String sql, int autoGeneratedKeys, java.lang.Object... args) {
    currentConnection = connection;
    try {
        java.sql.PreparedStatement stmt = (autoGeneratedKeys == (-1)) ? connection.prepareStatement(sql) : connection.prepareStatement(sql, autoGeneratedKeys);
        populatePreparedStatement(stmt, args);
        return stmt;
    } catch (java.sql.SQLException e) {
        throw new java.lang.RuntimeException(e);
    }
}