public java.util.LinkedList<searchclient.Node> findSolution(searchclient.Strategy strategy) {
    java.util.LinkedList<searchclient.Node> solution = new java.util.LinkedList<searchclient.Node>();
    searchclient.Node thePlan = findHighestPlan(this.agent, this.state);
    solution = implementHighPlan(thePlan, strategy);
    java.lang.System.err.println(("Solution generated by findHighestPlan: " + solution));
    return solution;
}